### ISSUE TITLE
wsrun changes my console.log output

### ISSUE THREAD

**Issue by LogvinovLeon** [hfour/wsrun#41]
Wsrun has this thing called prefixer and it changes my `console.log` output making it extremely difficult to debug. It's OK if you append the prefix to my output, but if you change stuff - that's not cool.

In particular paths.
It replaced 
```
/home/circleci/repo/contracts/multisig/contracts/multisig/MultiSigWalletWithTimeLock.sol
```
with 
```
/contracts/multisig/home/circleci/repo/contracts/multisig/contracts/multisig/MultiSigWalletWithTimeLock.sol
```
If you need more data - I have a repro for that.

I'm using the 2.x version, but 3.x is no different.

**Comment by spion** [comment]
Path replacement should be much better now. Let us know if the issue persists.

Another way to make wsrun pass through the output without any modifications is to use the `--no-prefix` option (however that will also remove the package name and pipe prefix)

**Comment by spion** [comment]
Reopening this because it seems more and more like the path replacement isn't a good idea and should maybe be removed.

**Comment by wh4everest** [comment]
Should we add an option to disable path rewriting, independently of `--no-prefix`?

**Comment by wh4everest** [comment]
A proposal, here: https://github.com/hfour/wsrun/pull/53

**Comment by spion** [comment]
Merged. Will write some release notes for version 4.0
