### ISSUE TITLE
Error with scoped packages

### ISSUE THREAD

**Issue by borekb** [hfour/wsrun#43]
I'm trying a basic example of

```
yarn wsrun -p @my/package test
```

and it just prints help and exists with an exit code 1.

I also tried:

- Add quotes: `yarn wsrun -p "@my/package" test`
- Use folder name instead of `name` in `package.json`: `yarn wsrun -p my-package test`

**Comment by spion** [comment]
Try `wsrun -p @my/package -c test`

**Comment by borekb** [comment]
Ah, thanks, it's even in the README but I didn't read the note:

> `yarn wsrun -p planc -c watch` will watch planc only. **Note that -c is passed here explicitly to denote the beginning of the command. This is needed because -p can accept multiple packages. (-c can also be substituted with -- but that generates warnings in yarn)**

Maybe it would be more intuitive if `wsrun -p @my/package test` just worked; `-p` help states that it can be used multiple times so this would be a way to run a script across multiple packages:

```
wsrun -p @my/package1 -p @my/package2 test
```

**Comment by spion** [comment]
@borekb 	due to the way yargs works it will always treat array arguments in the way you are seeing. better is to always require -c and i'll be updating the README.
