### ISSUE TITLE
Feature request: .wsrunrc config file

### ISSUE THREAD

**Issue by PaulRBerg** [hfour/wsrun#47]
I love this tool, but I think it would become even better if there was an option to set up a `.wsrunrc` config file. As per the latest v3 breaking chances, scripts looks rather verbose now:

```bash
wsrun --exclude-missing --fast-exit --package $PKG --recursive --stages build
```

Many of my scripts share the same options, such as `--exclude-missing` or `--fast-exit`. It would be nice to set them only once.

**Comment by spion** [comment]
you can put a shorthand in package.json

```json
{
  "wsrun-preset": "wsrun --exclude-missing --fast-exit --recursive --stages"
}
```
then you can use it:

```
yarn wsrun-preset -p package -c build
```

**Comment by PaulRBerg** [comment]
Many thanks for this, I'll give it a try.
