### ISSUE TITLE
wsrun is not recognized

### ISSUE THREAD

**Issue by Glinkis** [hfour/wsrun#54]
After upgrading to `4.0.0`, wsrun is no longer working.
I am using yarn workspaces, with `wsrun` installed at the root level. 

```
'wsrun' is not recognized as an internal or external command,
operable program or batch file.
```

If I downgrade to `3.6.6`, everything runs perfectly.

**Comment by spion** [comment]
Looks like the new binary directory was missing from the "files" package.json field.

Fixed in 4.0.2
