### ISSUE TITLE
Provide programmatic API

### ISSUE THREAD

**Issue by idan-at** [hfour/wsrun#64]
Hey,

Thanks for this tool! it helps us manage our yarn workspace.

However, there are some things we want to customize, that require running code on all packages.
A good example is synching a config file across all packages.

WDYS about exposing some kind of API? for example, allow iteration on all packages folders.

**Comment by spion** [comment]
Can you give a more specific example of what you would like to accomplish? 

Our typical pattern is to have a "tool" package in the monorepo that has a few ["bin" fields](https://docs.npmjs.com/files/package.json#bin) pointing to commonly used scripts. Then after a yarn install we're able to run

```
wsrun -c bin-script-name --args bin-script-args
```

**Comment by idan-at** [comment]
I'll try to give an example of what I mean.

with the current capabilities, I can run a command on all modules.
but let's say I want to do something a bit more complex:
Let's say I keep a `list.json` file of all my shared dependencies (names and versions), and I wish to update a major version of one of my dependencies.
Instead of doing it manually (editing each `package.json`), I want to run a script that does exactly that.

The problem is that this script doesn't know what modules I have in my workspace.
If I will be able to do something like this:

```js
const fs = require("fs");
const wsrun = require("wsrun");
const allModules = require("./list.json");

wsrun.packages.forEach(pkg => {
  const {name, path} = pkg;
  console.log(`update ${name}`);

  const packageJson = JSON.parse(fs.readFileSync(path));
  packageJson.dependencies = { ...packageJson.dependencies, ...allModules };

  fs.writeFileSync(path, JSON.stringify(packageJson), "utf-8");
})
```

It will be useful for those complex scenarios.

just to clarify, this is possible today by passing arguments to a script, but then I need to add an npm script inside each and every one of my modules, which kind of misses the point IMO.

**Comment by spion** [comment]
You don't need to add a npm script to every individual module.

Just make a module containing tool scripts, and make sure that they are specified in `"bin"` field of `package.json`. That will make them automatically available without having script entries in individual package.jsons

You can also use existing commands like that. For example, `yarn wsrun tsc` will run the typescript compiler command on every package, `yarn wsrun mocha` will run the mocha command in every package. As long as its found in `node_modules/.bin`, yarn will use it.

**Comment by idan-at** [comment]
I finally got it.

it works perfectly. Thanks.

closing :)
