### ISSUE TITLE
Build only if package has changed

### ISSUE THREAD

**Issue by lcswillems** [hfour/wsrun#77]
Hi,

First, thank you for this awesome package!! You saved me hours of setup!

It would be nice if `yarn wsrun --stages build` only builds packages that has changed since last command call.

Building all the packages takes 2 mns in my case, but often, I only change one small package and I have to rebuild everything.

Thank you,
Lucas Willems

**Comment by spion** [comment]
Hi! 

wsrun supports the `--if` option to which you can pass a command to check before running the main command. If you are able to write a command that checks whether a build is needed reliably you can pass it to that option.
