### ISSUE TITLE
Release wsrun?

### ISSUE THREAD

**Issue by devshorts** [hfour/wsrun#78]
Howdy, is it possible to cut a new release that has the fix for https://github.com/hfour/wsrun/pull/72? Thanks!

**Comment by erlichmen** [comment]
bump v5.0.2 doesn't seem to include #72

**Comment by devshorts** [comment]
@erlichmen if this is blocking you (like it was for me), I forked and published the latest to unblock.  I would love to have the official thing be released but if you want the working version (code unchanged, just published) you can grab it https://www.npmjs.com/package/@paradoxical-io/wsrun

**Comment by spion** [comment]
Its been published as 5.1.0 yesterday
