### ISSUE TITLE
Feature: --checkSum <checkSumFile> for storing information about package was changed from last command run, and do not run command again if the changes not affect package.

### ISSUE THREAD

**Issue by majo44** [hfour/wsrun#97]
**Problem:**
In multirepo we have some hierarchy of packages. We want to optimize the build in this way that we want to rebuild (or run tests, or compile, or ... ) only on packages which was not changed since we called command previous time. 
**Proposal:**
Proposal is to add `--checksum <checkSumFile>` parameter which will 
1. will try to read cwd `<checkSumFile>`
   - if file not exist the command will be run in all packages
   - if file exist command will be runned in packages only if:
       - there was not checksume for the package
       - the checkusme changed
       - the checksume of some dependency was changed
2. after command executed the `<checkSumFile>` file will be created and will contains
    - for each package where the command was run md5 checksum calculated by  
        - all files within the package filtered by .gitignore (also upper level node_modules)
        - all node_modules (also upper level node_modules) packages names+version 

**Behaviour with other options (in case of some conflicts)**
* `--changedSince` - command will be executed in rules of `--changedSince` so execution will be not filtered by current `<checkSumFile>`, but the `<checkSumFile>` will be updated/created, 

**Examples**
```
yarn wsrun --checksum .compilesum compile
yarn wsrun --checksum .buildsum build
yarn wsrun --checksum .buildsum test #reusing same sum file for build and test
```

**Comment by spion** [comment]
Have you considered using using `--if` and `--ifDependency` to implement this?

**Comment by majo44** [comment]
Yes, probably is possible to implement similar flow with `--if` and `--ifDependency`, but, as I understand how they work:
* This will require to for every task which you want to run with `--if` have a `<task>--needed` script: 'compile-needed', 'test-needed', 'build-needed' ect...
* I will need to overload all my N package.json files with that `<task>--needed` scripts
* No way to optimize eg: if package A and B depends on C, and I will want to eventually execute command on A and B, `<task>--needed` for C will be called twice, instead of once if such functionality w ill be build in, there is a lot more places to optimize (like node_modules, checksum calculation)

Proposed solution do not have any impact on `package.json` scripts, probably do not conflicts with other options. I do not know, is very specific for my flow or not. I think is common case when on monorepo, you want to rebuild only thinks which was changed since last rebuild. I have an monorepo of 15 packages, some 4 core libs and 11 "plugins", where the core depends each other, and plugins depends on cores. Each package is typescript, so for simple testing, i just need to compile it. From time to time I want to run the unit tests on changed packages. Much more rarely I need to make full build (lint, compile, generate docs, ...) 

I looked for the tool which will allows me to do not care where I making the changes but just by single command I'm able to rebuild (or just compile, or just run tests)  "whole" project, without care where (in which package) I made the changes. I found firstly https://www.npmjs.com/package/build-if-changed which is nice, but firstly I can run only 'build' script, and second problem that it is not take dependencies changes into account. Then I found `wsrun`, which is allows me to run any command, is calculating dependencies, ... but do net have `checksum` :)

**Comment by spion** [comment]
> I will need to overload all my N package.json files with that <task>--needed scripts

The script doesn't have to be listed in package.json - it can be any command that is available in `node_modules/.bin`

**Comment by majo44** [comment]
> The script doesn't have to be listed in package.json - it can be any command that is available in node_modules/.bin
That is good.
> --if-dependencies does that, if a dependency has re-built it will not run the check on the package instead it will immediately run the command on it.
I know that it why I think the `wsrun` is very close to what I need.

Ok lets try to model such `has-changes` script/tool:
So to "compile" my workspace:
```
yarn wsrun -s compile --if "has-changes .compile.sum" --if-dependencies "has-changes .compile.sum"
```
Problems:
1. If I have package A (without changes) which depends on B (with changes), command will be run firstly on B, so when it go to A, command will be not executed as now A and B do not have any changes. 
2. What with the case when command will be run for package A which did not changed, which depends on B which did not changed, which depends on C which has changes ?

**Comment by spion** [comment]
1. with if-dependencies, the command will also run for package `A`
2. I am not sure what that question means.

You might also want to look at https://github.com/hfour/ctsc/
